### ISSUE TITLE
Order create, user create notifications

### ISSUE THREAD

**Issue by anondev-sudo** [metallicgloss/WHMCS-Discord-Notifications#10]
Send webhook when user was created and user was registered.

**Comment by metallicgloss** [comment]
Neither of these notifications would provide any substantial benefit to the majority of the users of this script since the order creation notification serves no business purpose (more relevant notifications would be "Order Paid" and "Order Accepted") and notifications for the creation of a new user account is fairly pointless. The script is fully open source, so if these are an absolute requirement for your use case, please feel free to add them in, but I won't be building these into the generic script.
