### ISSUE TITLE
User name, avatar and link in embed author

### ISSUE THREAD

**Issue by anondev-sudo** [metallicgloss/WHMCS-Discord-Notifications#11]
When the action is triggered by some user, display first name, last name and email of the user + avatar in the embed author, and set link to the embed author url to user page in admin area.

**Comment by metallicgloss** [comment]
Including the full name and email address of the user triggering a notification to be sent may pose data protection issues should it be a customer performing the action.

Could you let me know specifically which notifications you were thinking of having these fields added to? To my knowledge, not many webhooks return any such information.

**Comment by anondev-sudo** [comment]
Invoice, ticket and order notifications

**Comment by anondev-sudo** [comment]
And that may be just optional, disabled by default

**Comment by metallicgloss** [comment]
Regrettably, this isn't something that is able to be added into this script at this time since the fields aren't available in the related webhooks - https://developers.whmcs.com/hooks/hook-index/ - should you wish for these to be included, you'd first need to submit a feature request to WHMCS to have them included in the hook.

**Comment by anondev-sudo** [comment]
Ok, btw there are built-in notification for slack, but I wonder why they didn't add also for discord? It's similar how slack and discord webhooks works

**Comment by metallicgloss** [comment]
This module is a third-party community script, so isn't associated directly with WHMCS, and therefore merely makes use of the public developer resources - the webhooks available for use are limited in their scope, hence the reason that there are certain restrictions on what can and can't be done without adding additional more complex API integration. This could be done should you wish to enhance it for your own installation, but considering that users still frequently struggle to follow the readme as it is, I don't intend on making it any more complex than it already is. The built in notification modules are able to take advantage of the API/built-in functionality much easier.

As for why they didn't add native support for Discord, I'm not too sure - likely because Discord is primarily used for communities, whereas Slack is more business focused (and will be the platform of choice for most WHMCS customers).
