### ISSUE TITLE
Today 10 Jan 2023 Notifications stoped working suddenly, as its been working from 2021

### ISSUE THREAD

**Issue by ITAshton** [metallicgloss/WHMCS-Discord-Notifications#14]
Today 10 Jan 2023 Notifications stopped working suddenly, as it's been working from 2021
I did create a new WebHook but still no notifications are going through, config is 100%

**Comment by shahidmallaofficial** [comment]
check cron job settings

**Comment by metallicgloss** [comment]
Regrettably, unlike a lot of other WHMCS addons that have built-in call-home functionality, this is a very simple open source PHP script so the configuration/functionality of it is totally dependent on the client-side configuration (meaning if it has stopped working, it isn't the result of a change to the script or this repo, and it would be somewhere in your setup).

If you have two installs of WHMCS on different servers, and they both stopped working in sync, my first recommendation would be to check the webhook that both installs are configured to point to - make sure it's still valid, hasn't been deleted, and hasn't been cycled (eg, changed/reset due to it being published publicly). I'd also suggest checking using online tools that other test scripts can send on the same webhook.

The second thing I'd look at is - are both servers setup for auto updates, or managed through a panel (like cPanel)? Check for errors in your php log to see if something broke simultaneously on both due to something being updated unexpectedly or config reverted.

The third thing I'd check is - are WHMCS hooks still being called? All this script does is send a webhook request when a hook is fired by WHMCS, so if the hook isn't being called or something within WHMCS is erroring out (check the logs), then it'd prevent it from running.

I hope one of the suggestions points you in the right direction!

**Comment by ITAshton** [comment]
> Regrettably, unlike a lot of other WHMCS addons that have built-in call-home functionality, this is a very simple open source PHP script so the configuration/functionality of it is totally dependent on the client-side configuration (meaning if it has stopped working, it isn't the result of a change to the script or this repo, and it would be somewhere in your setup).
> 
> If you have two installs of WHMCS on different servers, and they both stopped working in sync, my first recommendation would be to check the webhook that both installs are configured to point to - make sure it's still valid, hasn't been deleted, and hasn't been cycled (eg, changed/reset due to it being published publicly). I'd also suggest checking using online tools that other test scripts can send on the same webhook.
> 
> The second thing I'd look at is - are both servers setup for auto updates, or managed through a panel (like cPanel)? Check for errors in your php log to see if something broke simultaneously on both due to something being updated unexpectedly or config reverted.
> 
> The third thing I'd check is - are WHMCS hooks still being called? All this script does is send a webhook request when a hook is fired by WHMCS, so if the hook isn't being called or something within WHMCS is erroring out (check the logs), then it'd prevent it from running.
> 
> I hope one of the suggestions points you in the right direction!

Hi Metallicgloss,

You where right Discord changed the webhook URL on me, and I created a new webhook and all is well again, thank you very much for your in-depth answer I could learn from even for future problems, you are highly appreciated, Sir.

**Comment by metallicgloss** [comment]
No problem at all! 🙂 Glad it helped and it got the problem sorted!

**Comment by shahidmallaofficial** [comment]
I am going to update this. Tomorrow.


Thank you.
