### ISSUE TITLE
More detailed

### ISSUE THREAD

**Issue by anondev-sudo** [metallicgloss/WHMCS-Discord-Notifications#9]
Make it more detailed:
- when the action is associated with some user, display first name last name and email od the user + avatar in the embed author, and set link to the embed author irl to user page in admin area.
- display more info, like ticket subject, product names in order, ...

**Comment by metallicgloss** [comment]
Details that can be included in the notification are limited to the data that is returned from the specific webhook being called; ticket notifications for example already include details such as a snippet of the ticket message, ticket ID, ticket subject and link, and orders include generic details.

If there are additional fields returned by the specific webhook that you'd like added (https://developers.whmcs.com/hooks/hook-index/) please feel free to make a PR to add it in.

**Comment by anondev-sudo** [comment]
It wasn't completed

**Comment by anondev-sudo** [comment]
Don't close issues, keep it open so contributors can PR it when you don't want.

**Comment by metallicgloss** [comment]
Please refer to my previous comments with regards to the available fields that can be included from WHMCS.

**Comment by metallicgloss** [comment]
With regards to the closing of issues; different repos have different policies on this, and while I'm all for PRs for this repo, issues that are left open need to be detailed enough so that they can be of use to either myself or other contribute. Since your original request was very generic and didn't provide specifics, there would be little point leaving this open - should there be a specific notification that you'd like an additional available webhook field added to, please make a separate detailed issue.

I'll look into adding a contribution guideline to this repo in the near future to aid with this.
